// SolvTerra Mock Data
// @deprecated - This mock data is no longer used in production.
// Both apps now use Supabase with seed data (supabase/seed.sql).
// Mock IDs (e.g. 'challenge-1') do NOT match seed UUIDs.
// Kept for reference and offline testing only.

import type {
  Organization,
  User,
  Challenge,
  Submission,
  Badge,
  UserBadge,
  OrganizationStats,
  UserStats,
  NgoAdmin,
  Friend,
  TeammateSeeker,
  CommunityPost,
} from '../types';
import { AVAILABLE_BADGES, XP_BY_DURATION } from '../constants';

// ============================================
// MOCK TEAMMATE SEEKERS (for matchmaking demo)
// ============================================

export const MOCK_TEAMMATE_SEEKERS: TeammateSeeker[] = [
  {
    id: 'seeker-1',
    name: 'Sophie K.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SophieK',
    level: 'helper',
    joinedAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
  },
  {
    id: 'seeker-2',
    name: 'Niklas M.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NiklasM',
    level: 'starter',
    joinedAt: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
  },
  {
    id: 'seeker-3',
    name: 'Elena R.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ElenaR',
    level: 'supporter',
    joinedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
  },
];

// ============================================
// MOCK ORGANIZATIONS (German NGOs)
// Based on PRD Personas N1 (Small), N2 (Mid-Size), N3 (Large)
// ============================================

export const MOCK_ORGANIZATIONS: Organization[] = [
  // N1: Small Association - Local environmental group (Sweet Spot: easy to onboard, testimonials)
  {
    id: 'org-1',
    name: 'NABU Ortsgruppe Darmstadt',
    name_en: 'NABU Local Chapter Darmstadt',
    description: 'Die NABU Ortsgruppe Darmstadt setzt sich lokal für den Schutz von Natur und Umwelt ein. Wir engagieren uns für Artenvielfalt, Biotopschutz und Umweltbildung in unserer Region.',
    description_en: 'NABU Local Chapter Darmstadt advocates locally for the protection of nature and the environment. We are committed to biodiversity, habitat conservation and environmental education in our region.',
    mission: 'Für Natur und Umwelt in Darmstadt',
    mission_en: 'For nature and environment in Darmstadt',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=NABU&backgroundColor=2e6417',
    website: 'https://nabu-darmstadt.de',
    contactEmail: 'info@nabu-darmstadt.de',
    verified: true,
    verificationStatus: 'verified',
    ratingAvg: 4.7,
    ratingCount: 89,
    category: 'environment',
    createdAt: new Date('2025-01-15'),
  },
  // N2: Mid-Size NGO - PRIMARY TARGET (Regional welfare organization)
  {
    id: 'org-2',
    name: 'Tafel Rhein-Main e.V.',
    name_en: 'Food Bank Rhine-Main',
    description: 'Die Tafel Rhein-Main sammelt einwandfreie Lebensmittel und verteilt diese an über 15.000 Bedürftige in der Region. Wir sind auf engagierte Helfer angewiesen.',
    description_en: 'Food Bank Rhine-Main collects perfectly good food and distributes it to over 15,000 people in need in the region. We rely on dedicated volunteers.',
    mission: 'Lebensmittel retten. Menschen helfen.',
    mission_en: 'Save food. Help people.',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Tafel&backgroundColor=db2777',
    website: 'https://tafel-rheinmain.de',
    contactEmail: 'kontakt@tafel-rheinmain.de',
    verified: true,
    verificationStatus: 'verified',
    ratingAvg: 4.9,
    ratingCount: 456,
    category: 'social',
    createdAt: new Date('2025-02-01'),
  },
  // N2: Mid-Size NGO - Education focus
  {
    id: 'org-3',
    name: 'Bildungsinitiative Frankfurt',
    name_en: 'Education Initiative Frankfurt',
    description: 'Wir fördern Bildungschancen für Kinder und Jugendliche durch Nachhilfe, Lesepaten und digitale Lernprojekte an 12 Frankfurter Schulen.',
    description_en: 'We promote educational opportunities for children and young people through tutoring, reading mentors and digital learning projects at 12 Frankfurt schools.',
    mission: 'Bildung für alle',
    mission_en: 'Education for all',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=BIF&backgroundColor=7c3aed',
    website: 'https://bildungsinitiative-frankfurt.de',
    contactEmail: 'info@bildungsinitiative-frankfurt.de',
    verified: true,
    verificationStatus: 'verified',
    ratingAvg: 4.8,
    ratingCount: 134,
    category: 'education',
    createdAt: new Date('2025-03-10'),
  },
  // N1: Small Association - Animal welfare
  {
    id: 'org-4',
    name: 'Tierheim Darmstadt e.V.',
    name_en: 'Animal Shelter Darmstadt',
    description: 'Wir kümmern uns um über 200 herrenlose Tiere und vermitteln sie in liebevolle Zuhause. Unterstütze uns bei der täglichen Pflege!',
    description_en: 'We take care of over 200 homeless animals and place them in loving homes. Support us with the daily care!',
    mission: 'Ein Herz für Tiere',
    mission_en: 'A heart for animals',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=THD&backgroundColor=ea580c',
    website: 'https://tierheim-darmstadt.de',
    contactEmail: 'info@tierheim-darmstadt.de',
    verified: true,
    verificationStatus: 'verified',
    ratingAvg: 4.6,
    ratingCount: 156,
    category: 'animals',
    createdAt: new Date('2025-04-05'),
  },
  // N3: Large Organization - National humanitarian
  {
    id: 'org-5',
    name: 'Deutsches Rotes Kreuz Hessen',
    name_en: 'German Red Cross Hesse',
    description: 'Das DRK Hessen koordiniert humanitäre Hilfe, Rettungsdienste und soziale Arbeit. Mit über 50.000 Ehrenamtlichen sind wir im gesamten Bundesland aktiv.',
    description_en: 'The German Red Cross Hesse coordinates humanitarian aid, emergency services and social work. With over 50,000 volunteers, we are active throughout the state.',
    mission: 'Aus Liebe zum Menschen',
    mission_en: 'For the love of humanity',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=DRK&backgroundColor=dc2626',
    website: 'https://drk-hessen.de',
    contactEmail: 'info@drk-hessen.de',
    verified: true,
    verificationStatus: 'verified',
    ratingAvg: 4.8,
    ratingCount: 512,
    category: 'health',
    createdAt: new Date('2025-01-20'),
  },
  // N1: Small Association - Culture
  {
    id: 'org-6',
    name: 'Kulturbrücke Mainz',
    name_en: 'Cultural Bridge Mainz',
    description: 'Wir organisieren interkulturelle Veranstaltungen und fördern den Dialog zwischen Kulturen durch Kunst, Musik und gemeinsame Projekte.',
    description_en: 'We organize intercultural events and promote dialogue between cultures through art, music and collaborative projects.',
    mission: 'Kultur verbindet Menschen',
    mission_en: 'Culture connects people',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=KBM&backgroundColor=0891b2',
    website: 'https://kulturbruecke-mainz.de',
    contactEmail: 'info@kulturbruecke-mainz.de',
    verified: true,
    verificationStatus: 'verified',
    ratingAvg: 4.5,
    ratingCount: 67,
    category: 'culture',
    createdAt: new Date('2025-05-01'),
  },
  // N2: Mid-Size NGO - Senior care
  {
    id: 'org-7',
    name: 'Seniorenhilfe Rhein-Main e.V.',
    name_en: 'Senior Support Rhine-Main',
    description: 'Wir unterstützen über 2.000 ältere Menschen in der Region dabei, selbstständig und würdevoll zu leben. Unsere Angebote reichen von Besuchsdiensten bis zu digitaler Begleitung.',
    description_en: 'We support over 2,000 elderly people in the region to live independently and with dignity. Our services range from visiting services to digital companionship.',
    mission: 'Gemeinsam gegen Einsamkeit',
    mission_en: 'Together against loneliness',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=SHRM&backgroundColor=db2777',
    website: 'https://seniorenhilfe-rheinmain.de',
    contactEmail: 'kontakt@seniorenhilfe-rheinmain.de',
    verified: true,
    verificationStatus: 'verified',
    ratingAvg: 4.9,
    ratingCount: 278,
    category: 'social',
    createdAt: new Date('2025-02-15'),
  },
];

// ============================================
// MOCK CHALLENGES
// ============================================

export const MOCK_CHALLENGES: Challenge[] = [
  // Environment Challenges
  {
    id: 'chal-1',
    organizationId: 'org-1',
    organization: MOCK_ORGANIZATIONS[0],
    title: 'Müllsammelaktion im Park dokumentieren',
    title_en: 'Document trash cleanup in the park',
    description: 'Hilf uns, den öffentlichen Park sauber zu halten! Sammle Müll und dokumentiere deine Aktion mit Fotos.',
    description_en: 'Help us keep the public park clean! Collect trash and document your action with photos.',
    instructions: '1. Gehe in einen Park in deiner Nähe\n2. Sammle mindestens 10 Minuten lang Müll ein\n3. Mache ein Foto von dem gesammelten Müll\n4. Lade das Foto als Beweis hoch',
    instructions_en: '1. Go to a park near you\n2. Collect trash for at least 10 minutes\n3. Take a photo of the collected trash\n4. Upload the photo as proof',
    category: 'environment',
    type: 'onsite',
    durationMinutes: 15,
    verificationMethod: 'photo',
    maxParticipants: 50,
    currentParticipants: 23,
    xpReward: 30,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400',
    tags: ['outdoor', 'umwelt', 'müll'],
    // Location - flexible, any park
    location: {
      name: 'Beliebiger Park in deiner Nähe',
      name_en: 'Any park near you',
      additionalInfo: 'Handschuhe und Müllbeutel mitbringen!',
      additionalInfo_en: 'Bring gloves and trash bags!',
    },
    // Schedule - anytime
    schedule: {
      type: 'anytime',
      isFlexible: true,
    },
    // Contact
    contact: {
      name: 'Lisa Naturfreund',
      role: 'Umweltkoordinatorin',
      role_en: 'Environmental Coordinator',
      email: 'lisa@nabu-darmstadt.de',
      preferredMethod: 'email',
      responseTime: 'Innerhalb von 24 Stunden',
      responseTime_en: 'Within 24 hours',
    },
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-11-01'),
  },
  {
    id: 'chal-2',
    organizationId: 'org-1',
    organization: MOCK_ORGANIZATIONS[0],
    title: 'Social Media Post für Naturschutz erstellen',
    title_en: 'Create social media post for nature conservation',
    description: 'Erstelle einen kreativen Social Media Post, um auf den Naturschutz aufmerksam zu machen.',
    description_en: 'Create a creative social media post to raise awareness for nature conservation.',
    instructions: '1. Erstelle einen informativen Post über Naturschutz\n2. Verwende den Hashtag #NaturschutzJetzt\n3. Poste auf Instagram, Twitter oder LinkedIn\n4. Mache einen Screenshot und lade ihn hoch',
    instructions_en: '1. Create an informative post about nature conservation\n2. Use the hashtag #NatureConservationNow\n3. Post on Instagram, Twitter or LinkedIn\n4. Take a screenshot and upload it',
    category: 'environment',
    type: 'digital',
    durationMinutes: 10,
    verificationMethod: 'photo',
    maxParticipants: 100,
    currentParticipants: 45,
    xpReward: 20,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400',
    tags: ['social-media', 'digital', 'awareness'],
    // Schedule - deadline-based campaign
    schedule: {
      type: 'range',
      startDate: new Date('2025-12-01'),
      endDate: new Date('2025-12-31'),
      deadline: new Date('2025-12-31'),
      isFlexible: true,
    },
    contact: {
      name: 'Lisa Naturfreund',
      role: 'Social Media Team',
      role_en: 'Social Media Team',
      email: 'social@nabu-darmstadt.de',
      preferredMethod: 'email',
      responseTime: 'Innerhalb von 48 Stunden',
      responseTime_en: 'Within 48 hours',
    },
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2025-11-10'),
  },

  // Social Challenges
  {
    id: 'chal-3',
    organizationId: 'org-2',
    organization: MOCK_ORGANIZATIONS[1],
    title: 'Lebensmittel sortieren bei der Tafel',
    title_en: 'Sort food at the food bank',
    description: 'Hilf uns beim Sortieren von gespendeten Lebensmitteln in unserer Ausgabestelle.',
    description_en: 'Help us sort donated food at our distribution center.',
    instructions: '1. Komme zur Tafel-Ausgabestelle in Frankfurt\n2. Hilf beim Sortieren der Lebensmittel nach Haltbarkeit\n3. Mache ein Foto bei der Arbeit\n4. Lade das Foto hoch',
    instructions_en: '1. Come to the food bank distribution center in Frankfurt\n2. Help sort food by expiration date\n3. Take a photo while working\n4. Upload the photo',
    category: 'social',
    type: 'onsite',
    durationMinutes: 30,
    verificationMethod: 'photo',
    maxParticipants: 10,
    currentParticipants: 4,
    xpReward: 50,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=400',
    tags: ['vor-ort', 'teamwork', 'lebensmittel'],
    location: {
      name: 'Tafel Ausgabestelle Frankfurt-Bockenheim',
      name_en: 'Food Bank Distribution Center Frankfurt-Bockenheim',
      address: 'Leipziger Straße 45, 60487 Frankfurt am Main',
      meetingPoint: 'Hintereingang (Schild "Ehrenamtliche")',
      meetingPoint_en: 'Back entrance (sign "Volunteers")',
      additionalInfo: 'Bitte bequeme Kleidung tragen. Handschuhe werden gestellt.',
      additionalInfo_en: 'Please wear comfortable clothing. Gloves are provided.',
      coordinates: { lat: 50.1155, lng: 8.6724 },
    },
    schedule: {
      type: 'recurring',
      timeSlots: ['Mo, Mi, Fr: 9-12 Uhr', 'Di, Do: 14-17 Uhr'],
      deadline: new Date('2026-01-31'),
      isFlexible: false,
    },
    contact: {
      name: 'Michael Helfer',
      role: 'Ehrenamtskoordinator',
      role_en: 'Volunteer Coordinator',
      email: 'ehrenamt@tafel-rheinmain.de',
      phone: '+49 69 1234567',
      preferredMethod: 'phone',
      responseTime: 'Sofort während Öffnungszeiten',
      responseTime_en: 'Immediately during opening hours',
    },
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: 'chal-4',
    organizationId: 'org-7',
    organization: MOCK_ORGANIZATIONS[6],
    title: 'Telefonat mit Senioren führen',
    title_en: 'Have a phone call with seniors',
    description: 'Führe ein nettes Telefonat mit einem einsamen Senior oder einer Seniorin. Dein Anruf macht den Unterschied!',
    description_en: 'Have a nice phone call with a lonely senior. Your call makes a difference!',
    instructions: '1. Melde dich bei uns an – wir vermitteln dir einen Kontakt\n2. Rufe die zugewiesene Person an und führe ein freundliches Gespräch\n3. Das Gespräch sollte mindestens 15 Minuten dauern\n4. Schreibe uns danach eine kurze Zusammenfassung (2-3 Sätze)',
    instructions_en: '1. Sign up with us - we will connect you with someone\n2. Call the assigned person and have a friendly conversation\n3. The conversation should last at least 15 minutes\n4. Send us a short summary afterwards (2-3 sentences)',
    category: 'social',
    type: 'digital',
    durationMinutes: 15,
    verificationMethod: 'text',
    maxParticipants: 20,
    currentParticipants: 8,
    xpReward: 30,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1516728778615-2d590ea1855e?w=400',
    tags: ['telefonat', 'senioren', 'gespräch'],
    schedule: {
      type: 'recurring',
      timeSlots: ['Täglich 10-12 Uhr', 'Täglich 15-18 Uhr'],
      isFlexible: true,
    },
    contact: {
      name: 'Claudia Warmherz',
      role: 'Projektleiterin Besuchsdienst',
      role_en: 'Project Manager Visiting Service',
      email: 'besuchsdienst@seniorenhilfe-rheinmain.de',
      phone: '+49 69 9876543',
      preferredMethod: 'email',
      responseTime: 'Innerhalb von 24 Stunden',
      responseTime_en: 'Within 24 hours',
    },
    createdAt: new Date('2025-11-18'),
    updatedAt: new Date('2025-12-01'),
  },

  // Education Challenges
  {
    id: 'chal-5',
    organizationId: 'org-3',
    organization: MOCK_ORGANIZATIONS[2],
    title: 'Kinderbuch-Empfehlungen recherchieren',
    title_en: 'Research children\'s book recommendations',
    description: 'Recherchiere 5 altersgerechte Kinderbücher für Grundschüler und erstelle eine Empfehlungsliste für unsere Lesepaten.',
    description_en: 'Research 5 age-appropriate children\'s books for elementary school students and create a recommendation list for our reading mentors.',
    instructions: '1. Recherchiere 5 Kinderbücher für 6-10 Jährige\n2. Achte auf diverse Themen und Autor:innen\n3. Schreibe zu jedem Buch eine kurze Empfehlung (2-3 Sätze)\n4. Reiche deine Liste als Text ein',
    instructions_en: '1. Research 5 children\'s books for ages 6-10\n2. Look for diverse topics and authors\n3. Write a short recommendation for each book (2-3 sentences)\n4. Submit your list as text',
    category: 'education',
    type: 'digital',
    durationMinutes: 15,
    verificationMethod: 'text',
    maxParticipants: 30,
    currentParticipants: 12,
    xpReward: 30,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    tags: ['recherche', 'bücher', 'kinder'],
    schedule: {
      type: 'range',
      startDate: new Date('2025-12-01'),
      endDate: new Date('2026-01-15'),
      deadline: new Date('2026-01-15'),
      isFlexible: true,
    },
    contact: {
      name: 'Dr. Sarah Bildung',
      role: 'Projektkoordinatorin Leseförderung',
      role_en: 'Project Coordinator Reading Support',
      email: 'lesefoerderung@bildungsinitiative-frankfurt.de',
      preferredMethod: 'email',
      responseTime: 'Innerhalb von 48 Stunden',
      responseTime_en: 'Within 48 hours',
    },
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: 'chal-6',
    organizationId: 'org-3',
    organization: MOCK_ORGANIZATIONS[2],
    title: 'Vorlese-Video aufnehmen',
    title_en: 'Record a reading video',
    description: 'Nimm ein kurzes Video auf, in dem du eine Geschichte für Kinder vorliest. Dein Video wird auf unserer Lernplattform verwendet!',
    description_en: 'Record a short video reading a story for children. Your video will be used on our learning platform!',
    instructions: '1. Wähle eine kindgerechte Geschichte aus (max. 5 Minuten)\n2. Achte auf gute Beleuchtung und klaren Ton\n3. Nimm dich beim Vorlesen auf\n4. Lade das Video hoch oder teile einen Google Drive / Dropbox Link',
    instructions_en: '1. Choose a child-friendly story (max. 5 minutes)\n2. Ensure good lighting and clear audio\n3. Record yourself reading\n4. Upload the video or share a Google Drive / Dropbox link',
    category: 'education',
    type: 'digital',
    durationMinutes: 10,
    verificationMethod: 'text',
    maxParticipants: 25,
    currentParticipants: 7,
    xpReward: 20,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400',
    tags: ['video', 'vorlesen', 'kreativ'],
    schedule: {
      type: 'anytime',
      isFlexible: true,
    },
    contact: {
      name: 'Markus Lernfreund',
      role: 'Medienkoordinator',
      role_en: 'Media Coordinator',
      email: 'medien@bildungsinitiative-frankfurt.de',
      preferredMethod: 'email',
      responseTime: 'Innerhalb von 24 Stunden',
      responseTime_en: 'Within 24 hours',
    },
    createdAt: new Date('2025-11-22'),
    updatedAt: new Date('2025-12-01'),
  },

  // Health Challenges
  {
    id: 'chal-7',
    organizationId: 'org-5',
    organization: MOCK_ORGANIZATIONS[4],
    title: 'Erste-Hilfe-Wissen teilen',
    title_en: 'Share first aid knowledge',
    description: 'Erstelle einen informativen Post über grundlegende Erste-Hilfe-Maßnahmen und erreiche damit deine Community.',
    description_en: 'Create an informative post about basic first aid measures and reach your community.',
    instructions: '1. Recherchiere grundlegende Erste-Hilfe-Maßnahmen auf unserer Website\n2. Erstelle einen informativen Social-Media-Post (Infografik oder Text)\n3. Teile ihn mit dem Hashtag #ErsteHilfeRettet\n4. Lade einen Screenshot deines Posts hoch',
    instructions_en: '1. Research basic first aid measures on our website\n2. Create an informative social media post (infographic or text)\n3. Share it with the hashtag #FirstAidSaves\n4. Upload a screenshot of your post',
    category: 'health',
    type: 'digital',
    durationMinutes: 15,
    verificationMethod: 'photo',
    maxParticipants: 50,
    currentParticipants: 18,
    xpReward: 30,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400',
    tags: ['gesundheit', 'erste-hilfe', 'social-media'],
    schedule: {
      type: 'range',
      startDate: new Date('2025-12-01'),
      endDate: new Date('2026-01-31'),
      deadline: new Date('2026-01-31'),
      isFlexible: true,
    },
    contact: {
      name: 'Thomas Rettung',
      role: 'Referent Öffentlichkeitsarbeit',
      role_en: 'Public Relations Officer',
      email: 'presse@drk-hessen.de',
      phone: '+49 611 5060100',
      preferredMethod: 'email',
      responseTime: 'Innerhalb von 48 Stunden',
      responseTime_en: 'Within 48 hours',
    },
    createdAt: new Date('2025-11-25'),
    updatedAt: new Date('2025-12-01'),
  },

  // Animal Challenges
  {
    id: 'chal-8',
    organizationId: 'org-4',
    organization: MOCK_ORGANIZATIONS[3],
    title: 'Tierheim-Tiere auf Social Media vorstellen',
    title_en: 'Feature shelter animals on social media',
    description: 'Hilf uns, unsere Tiere bekannt zu machen! Teile ein Profil eines unserer Schützlinge und erhöhe die Vermittlungschancen.',
    description_en: 'Help us make our animals known! Share a profile of one of our residents and increase their adoption chances.',
    instructions: '1. Besuche unsere Website www.tierheim-darmstadt.de und wähle ein Tier aus\n2. Erstelle einen ansprechenden Social-Media-Post über das Tier\n3. Beschreibe Charakter und Besonderheiten\n4. Teile den Post mit #TierheimDarmstadt und lade einen Screenshot hoch',
    instructions_en: '1. Visit our website www.tierheim-darmstadt.de and choose an animal\n2. Create an appealing social media post about the animal\n3. Describe its character and special features\n4. Share the post with #ShelterDarmstadt and upload a screenshot',
    category: 'animals',
    type: 'digital',
    durationMinutes: 10,
    verificationMethod: 'photo',
    maxParticipants: 40,
    currentParticipants: 15,
    xpReward: 20,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400',
    tags: ['tiere', 'social-media', 'adoption'],
    schedule: {
      type: 'anytime',
      isFlexible: true,
    },
    contact: {
      name: 'Julia Tierlieb',
      role: 'Vermittlungskoordinatorin',
      role_en: 'Adoption Coordinator',
      email: 'vermittlung@tierheim-darmstadt.de',
      phone: '+49 6151 52523',
      preferredMethod: 'email',
      responseTime: 'Innerhalb von 24 Stunden',
      responseTime_en: 'Within 24 hours',
    },
    createdAt: new Date('2025-11-28'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: 'chal-9',
    organizationId: 'org-4',
    organization: MOCK_ORGANIZATIONS[3],
    title: 'Hundespaziergang im Tierheim',
    title_en: 'Dog walking at the shelter',
    description: 'Geh mit einem unserer Hunde spazieren und schenke ihm Aufmerksamkeit. Die Hunde freuen sich riesig über Abwechslung!',
    description_en: 'Walk one of our dogs and give them attention. The dogs love the variety!',
    instructions: '1. Komme zum Tierheim Darmstadt\n2. Melde dich am Empfang für einen Hundespaziergang an\n3. Unsere Mitarbeiter:innen teilen dir einen passenden Hund zu\n4. Gehe mindestens 20 Minuten mit dem Hund spazieren\n5. Mache ein Foto während des Spaziergangs',
    instructions_en: '1. Come to the Darmstadt Animal Shelter\n2. Register at reception for a dog walk\n3. Our staff will assign you a suitable dog\n4. Walk with the dog for at least 20 minutes\n5. Take a photo during the walk',
    category: 'animals',
    type: 'onsite',
    durationMinutes: 30,
    verificationMethod: 'photo',
    maxParticipants: 8,
    currentParticipants: 3,
    xpReward: 50,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400',
    tags: ['vor-ort', 'hunde', 'bewegung'],
    location: {
      name: 'Tierheim Darmstadt',
      name_en: 'Animal Shelter Darmstadt',
      address: 'Eschollbrücker Straße 100, 64295 Darmstadt',
      meetingPoint: 'Empfang im Hauptgebäude',
      meetingPoint_en: 'Reception in the main building',
      additionalInfo: 'Festes Schuhwerk empfohlen. Hunde werden vom Personal zugeteilt.',
      additionalInfo_en: 'Sturdy footwear recommended. Dogs are assigned by staff.',
      coordinates: { lat: 49.8498, lng: 8.6264 },
    },
    schedule: {
      type: 'recurring',
      timeSlots: ['Di-Fr: 14-17 Uhr', 'Sa-So: 10-16 Uhr'],
      isFlexible: false,
    },
    contact: {
      name: 'Peter Hundefreund',
      role: 'Hundebetreuer',
      role_en: 'Dog Caretaker',
      email: 'hunde@tierheim-darmstadt.de',
      phone: '+49 6151 52523',
      preferredMethod: 'phone',
      responseTime: 'Sofort während Öffnungszeiten',
      responseTime_en: 'Immediately during opening hours',
    },
    createdAt: new Date('2025-11-30'),
    updatedAt: new Date('2025-12-01'),
  },

  // Culture Challenges
  {
    id: 'chal-10',
    organizationId: 'org-6',
    organization: MOCK_ORGANIZATIONS[5],
    title: 'Kulturveranstaltung dokumentieren',
    title_en: 'Document a cultural event',
    description: 'Dokumentiere eine kulturelle Veranstaltung in deiner Stadt mit Fotos für unseren Blog und Social Media.',
    description_en: 'Document a cultural event in your city with photos for our blog and social media.',
    instructions: '1. Besuche eine kulturelle Veranstaltung (Museum, Konzert, Theater, Ausstellung)\n2. Mache 3-5 hochwertige Fotos von der Veranstaltung\n3. Achte auf gute Bildkomposition und Beleuchtung\n4. Lade dein bestes Foto mit kurzer Beschreibung hoch',
    instructions_en: '1. Visit a cultural event (museum, concert, theater, exhibition)\n2. Take 3-5 high-quality photos of the event\n3. Pay attention to good composition and lighting\n4. Upload your best photo with a short description',
    category: 'culture',
    type: 'onsite',
    durationMinutes: 30,
    verificationMethod: 'photo',
    maxParticipants: 25,
    currentParticipants: 9,
    xpReward: 50,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400',
    tags: ['kultur', 'fotos', 'veranstaltung'],
    location: {
      name: 'Beliebige Kulturveranstaltung in der Region',
      name_en: 'Any cultural event in the region',
      additionalInfo: 'Museen, Theater, Konzerte, Ausstellungen – alles ist willkommen!',
      additionalInfo_en: 'Museums, theaters, concerts, exhibitions - everything is welcome!',
    },
    schedule: {
      type: 'range',
      startDate: new Date('2025-12-01'),
      endDate: new Date('2026-02-28'),
      deadline: new Date('2026-02-28'),
      isFlexible: true,
    },
    contact: {
      name: 'Amir Kulturbrücke',
      role: 'Projektleiter Kulturvermittlung',
      role_en: 'Project Manager Cultural Outreach',
      email: 'projekte@kulturbruecke-mainz.de',
      preferredMethod: 'email',
      responseTime: 'Innerhalb von 48 Stunden',
      responseTime_en: 'Within 48 hours',
    },
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2025-12-01'),
  },

  // Quick 5-minute challenges
  {
    id: 'chal-11',
    organizationId: 'org-1',
    organization: MOCK_ORGANIZATIONS[0],
    title: 'Umwelt-Umfrage ausfüllen',
    title_en: 'Complete environmental survey',
    description: 'Fülle unsere kurze Umfrage zum Umweltbewusstsein aus. Deine Antworten helfen uns bei der Planung neuer Projekte!',
    description_en: 'Complete our short survey on environmental awareness. Your answers help us plan new projects!',
    instructions: '1. Klicke auf den Umfrage-Link in unserer App\n2. Beantworte alle 8 Fragen ehrlich (ca. 5 Min)\n3. Sende uns die Bestätigungsnummer als Text',
    instructions_en: '1. Click on the survey link in our app\n2. Answer all 8 questions honestly (approx. 5 min)\n3. Send us the confirmation number as text',
    category: 'environment',
    type: 'digital',
    durationMinutes: 5,
    verificationMethod: 'text',
    maxParticipants: 200,
    currentParticipants: 87,
    xpReward: 10,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400',
    tags: ['umfrage', 'schnell', 'digital'],
    schedule: {
      type: 'range',
      startDate: new Date('2025-12-01'),
      endDate: new Date('2026-01-31'),
      deadline: new Date('2026-01-31'),
      isFlexible: true,
    },
    contact: {
      name: 'Lisa Naturfreund',
      role: 'Umweltkoordinatorin',
      role_en: 'Environmental Coordinator',
      email: 'umfrage@nabu-darmstadt.de',
      preferredMethod: 'email',
      responseTime: 'Automatische Bestätigung',
      responseTime_en: 'Automatic confirmation',
    },
    createdAt: new Date('2025-12-02'),
    updatedAt: new Date('2025-12-02'),
  },
  {
    id: 'chal-12',
    organizationId: 'org-5',
    organization: MOCK_ORGANIZATIONS[4],
    title: 'Blutspende-Info teilen',
    title_en: 'Share blood donation info',
    description: 'Teile Informationen über Blutspende in deinem sozialen Umfeld. Jeder Beitrag kann Leben retten!',
    description_en: 'Share information about blood donation with your social circle. Every post can save lives!',
    instructions: '1. Informiere dich auf www.drk-blutspende.de über Blutspende\n2. Teile den Info-Beitrag in deinen sozialen Medien oder WhatsApp\n3. Schreibe dazu, warum Blutspenden wichtig ist\n4. Mache einen Screenshot und lade ihn hoch',
    instructions_en: '1. Learn about blood donation at www.drk-blutspende.de\n2. Share the info post on your social media or WhatsApp\n3. Write why blood donation is important\n4. Take a screenshot and upload it',
    category: 'health',
    type: 'digital',
    durationMinutes: 5,
    verificationMethod: 'photo',
    maxParticipants: 150,
    currentParticipants: 62,
    xpReward: 10,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=400',
    tags: ['blutspende', 'teilen', 'schnell'],
    schedule: {
      type: 'anytime',
      isFlexible: true,
    },
    contact: {
      name: 'Dr. Karin Blutspende',
      role: 'Leiterin Spenderwerbung',
      role_en: 'Head of Donor Recruitment',
      email: 'blutspende@drk-hessen.de',
      phone: '+49 611 5060200',
      preferredMethod: 'email',
      responseTime: 'Innerhalb von 24 Stunden',
      responseTime_en: 'Within 24 hours',
    },
    createdAt: new Date('2025-12-03'),
    updatedAt: new Date('2025-12-03'),
  },

  // ============================================
  // MULTI-PERSON / TEAM CHALLENGES
  // Showcasing the social USP - 62% would help more with friends
  // ============================================
  {
    id: 'chal-team-1',
    organizationId: 'org-1',
    organization: MOCK_ORGANIZATIONS[0],
    title: 'Gemeinsame Müllsammelaktion',
    title_en: 'Team trash cleanup',
    description: 'Sammelt gemeinsam als Team Müll im Herrngarten Darmstadt. Zusammen schafft ihr mehr und habt dabei Spaß!',
    description_en: 'Collect trash together as a team in Herrngarten Darmstadt. Together you accomplish more and have fun!',
    instructions: '1. Bildet ein Team von 2-4 Personen\n2. Trefft euch am großen Springbrunnen im Herrngarten\n3. Sammelt 30 Minuten gemeinsam Müll\n4. Handschuhe und Müllbeutel werden vor Ort gestellt\n5. Macht ein Gruppenfoto mit dem gesammelten Müll\n6. Ladet das Foto zusammen hoch',
    instructions_en: '1. Form a team of 2-4 people\n2. Meet at the large fountain in Herrngarten\n3. Collect trash together for 30 minutes\n4. Gloves and trash bags are provided on site\n5. Take a group photo with the collected trash\n6. Upload the photo together',
    category: 'environment',
    type: 'onsite',
    durationMinutes: 30,
    verificationMethod: 'photo',
    maxParticipants: 40,
    currentParticipants: 12,
    xpReward: 75,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1567393528677-d6adae7d4a0a?w=400',
    tags: ['team', 'outdoor', 'umwelt'],
    isMultiPerson: true,
    minTeamSize: 2,
    maxTeamSize: 4,
    teamDescription: 'Lade Freunde ein oder finde neue Teammitglieder über unsere Matching-Funktion!',
    teamDescription_en: 'Invite friends or find new team members through our matching feature!',
    allowSoloJoin: true,
    teammateSeekers: MOCK_TEAMMATE_SEEKERS.slice(0, 2),
    location: {
      name: 'Herrngarten Darmstadt',
      name_en: 'Herrngarten Park Darmstadt',
      address: 'Herrngarten, 64283 Darmstadt',
      meetingPoint: 'Am großen Springbrunnen (Nordseite)',
      meetingPoint_en: 'At the large fountain (north side)',
      additionalInfo: 'Handschuhe und Müllbeutel werden gestellt. Bitte wetterfeste Kleidung tragen.',
      additionalInfo_en: 'Gloves and trash bags are provided. Please wear weather-appropriate clothing.',
      coordinates: { lat: 49.8728, lng: 8.6512 },
    },
    schedule: {
      type: 'fixed',
      startDate: new Date('2025-12-13T10:00:00'),
      endDate: new Date('2025-12-13T11:00:00'),
      isFlexible: false,
    },
    contact: {
      name: 'Lisa Naturfreund',
      role: 'Aktionsleitung',
      role_en: 'Event Leader',
      email: 'aktionen@nabu-darmstadt.de',
      phone: '+49 6151 987654',
      preferredMethod: 'app',
      responseTime: 'Innerhalb von 2 Stunden',
      responseTime_en: 'Within 2 hours',
    },
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: 'chal-team-2',
    organizationId: 'org-3',
    organization: MOCK_ORGANIZATIONS[2],
    title: 'Team-Recherche: Bildungsmaterialien',
    title_en: 'Team research: Educational materials',
    description: 'Recherchiert als Team kostenlose Lernressourcen für Grundschüler. Eure Ergebnisse helfen Kindern beim Lernen!',
    description_en: 'Research free learning resources for elementary students as a team. Your results help children learn!',
    instructions: '1. Bildet ein Team von 2-3 Personen\n2. Teilt die Recherche nach Fächern auf (Mathe, Deutsch, Sachkunde)\n3. Findet mindestens 10 kostenlose Online-Lernressourcen\n4. Bewertet jede Ressource kurz (Altersgruppe, Qualität)\n5. Erstellt gemeinsam eine strukturierte Liste\n6. Reicht die Liste als Text oder Google Doc Link ein',
    instructions_en: '1. Form a team of 2-3 people\n2. Divide the research by subjects (Math, German, Science)\n3. Find at least 10 free online learning resources\n4. Briefly rate each resource (age group, quality)\n5. Create a structured list together\n6. Submit the list as text or Google Doc link',
    category: 'education',
    type: 'digital',
    durationMinutes: 15,
    verificationMethod: 'text',
    maxParticipants: 30,
    currentParticipants: 6,
    xpReward: 45,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400',
    tags: ['team', 'recherche', 'bildung'],
    isMultiPerson: true,
    minTeamSize: 2,
    maxTeamSize: 3,
    teamDescription: 'Gemeinsam recherchiert es sich besser! Teilt euch die Fächer auf.',
    teamDescription_en: 'Research is better together! Split up the subjects.',
    allowSoloJoin: true,
    teammateSeekers: [MOCK_TEAMMATE_SEEKERS[2]],
    schedule: {
      type: 'range',
      startDate: new Date('2025-12-01'),
      endDate: new Date('2026-01-15'),
      deadline: new Date('2026-01-15'),
      isFlexible: true,
    },
    contact: {
      name: 'Dr. Sarah Bildung',
      role: 'Projektkoordinatorin',
      role_en: 'Project Coordinator',
      email: 'projekte@bildungsinitiative-frankfurt.de',
      preferredMethod: 'email',
      responseTime: 'Innerhalb von 24 Stunden',
      responseTime_en: 'Within 24 hours',
    },
    createdAt: new Date('2025-12-02'),
    updatedAt: new Date('2025-12-02'),
  },
  {
    id: 'chal-team-3',
    organizationId: 'org-2',
    organization: MOCK_ORGANIZATIONS[1],
    title: 'Flyer verteilen im Team',
    title_en: 'Distribute flyers as a team',
    description: 'Verteilt als Gruppe Flyer für die Tafel in Frankfurt-Nordend. Mit mehr Leuten erreicht ihr mehr Menschen!',
    description_en: 'Distribute flyers for the food bank in Frankfurt-Nordend as a group. With more people, you reach more people!',
    instructions: '1. Bildet ein Team von 2-5 Personen\n2. Holt die Flyer bei der Tafel in Bockenheim ab (Leipziger Str. 45)\n3. Verteilt sie im Gebiet Frankfurt-Nordend (Karte wird bereitgestellt)\n4. Macht Fotos während der Verteilung\n5. Ladet ein Gruppenfoto hoch',
    instructions_en: '1. Form a team of 2-5 people\n2. Pick up flyers at the food bank in Bockenheim (Leipziger Str. 45)\n3. Distribute them in Frankfurt-Nordend area (map provided)\n4. Take photos during distribution\n5. Upload a group photo',
    category: 'social',
    type: 'onsite',
    durationMinutes: 30,
    verificationMethod: 'photo',
    maxParticipants: 25,
    currentParticipants: 5,
    xpReward: 60,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400',
    tags: ['team', 'vor-ort', 'flyer'],
    isMultiPerson: true,
    minTeamSize: 2,
    maxTeamSize: 5,
    teamDescription: 'Mit mehr Leuten erreicht ihr mehr Menschen! Lade Freunde ein.',
    teamDescription_en: 'With more people, you reach more people! Invite friends.',
    allowSoloJoin: true,
    teammateSeekers: MOCK_TEAMMATE_SEEKERS.slice(1, 3),
    location: {
      name: 'Tafel Ausgabestelle Frankfurt-Bockenheim (Abholung)',
      name_en: 'Food Bank Frankfurt-Bockenheim (Pickup)',
      address: 'Leipziger Straße 45, 60487 Frankfurt am Main',
      meetingPoint: 'Haupteingang – Flyer werden dort ausgegeben',
      meetingPoint_en: 'Main entrance - flyers are handed out there',
      additionalInfo: 'Verteilgebiet: Frankfurt-Nordend. Gebietskarte wird vor Ort ausgeteilt.',
      additionalInfo_en: 'Distribution area: Frankfurt-Nordend. Area map provided on site.',
      coordinates: { lat: 50.1155, lng: 8.6724 },
    },
    schedule: {
      type: 'recurring',
      timeSlots: ['Sa: 10-13 Uhr', 'So: 14-17 Uhr'],
      deadline: new Date('2026-01-31'),
      isFlexible: false,
    },
    contact: {
      name: 'Michael Helfer',
      role: 'Ehrenamtskoordinator',
      role_en: 'Volunteer Coordinator',
      email: 'ehrenamt@tafel-rheinmain.de',
      phone: '+49 69 1234567',
      preferredMethod: 'phone',
      responseTime: 'Sofort während Bürozeiten',
      responseTime_en: 'Immediately during office hours',
    },
    createdAt: new Date('2025-12-03'),
    updatedAt: new Date('2025-12-03'),
  },
  {
    id: 'chal-team-4',
    organizationId: 'org-6',
    organization: MOCK_ORGANIZATIONS[5],
    title: 'Interkulturelles Kochevent dokumentieren',
    title_en: 'Document intercultural cooking event',
    description: 'Organisiert ein kleines interkulturelles Kochevent und dokumentiert es für unseren Blog. Feiert Vielfalt gemeinsam!',
    description_en: 'Organize a small intercultural cooking event and document it for our blog. Celebrate diversity together!',
    instructions: '1. Bildet ein Team von 3-4 Personen aus verschiedenen Kulturen\n2. Kocht gemeinsam ein traditionelles Gericht aus einer eurer Kulturen\n3. Dokumentiert das Event mit mind. 5 Fotos (Zutaten, Kochen, fertiges Gericht, Gruppe)\n4. Schreibt eine kurze Beschreibung des Rezepts und der kulturellen Bedeutung\n5. Erstellt einen Social-Media-Beitrag mit #KulturbrückeMainz\n6. Teilt den Beitrag und ladet Screenshots + Fotos hoch',
    instructions_en: '1. Form a team of 3-4 people from different cultures\n2. Cook a traditional dish from one of your cultures together\n3. Document the event with at least 5 photos (ingredients, cooking, finished dish, group)\n4. Write a short description of the recipe and its cultural significance\n5. Create a social media post with #CulturalBridgeMainz\n6. Share the post and upload screenshots + photos',
    category: 'culture',
    type: 'onsite',
    durationMinutes: 30,
    verificationMethod: 'photo',
    maxParticipants: 20,
    currentParticipants: 8,
    xpReward: 70,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
    tags: ['team', 'kultur', 'kochen', 'interkulturell'],
    isMultiPerson: true,
    minTeamSize: 3,
    maxTeamSize: 4,
    teamDescription: 'Feiert Vielfalt gemeinsam! Findet Teammitglieder aus verschiedenen Kulturen.',
    teamDescription_en: 'Celebrate diversity together! Find team members from different cultures.',
    allowSoloJoin: true,
    teammateSeekers: MOCK_TEAMMATE_SEEKERS,
    location: {
      name: 'Eigene Küche oder Gemeinschaftsraum',
      name_en: 'Your own kitchen or community room',
      additionalInfo: 'Ihr organisiert den Ort selbst. Tipp: Nutzt studentische Gemeinschaftsküchen oder trefft euch privat.',
      additionalInfo_en: 'You organize the location yourself. Tip: Use student community kitchens or meet privately.',
    },
    schedule: {
      type: 'range',
      startDate: new Date('2025-12-01'),
      endDate: new Date('2026-02-28'),
      deadline: new Date('2026-02-28'),
      isFlexible: true,
    },
    contact: {
      name: 'Amir Kulturbrücke',
      role: 'Projektleiter Interkulturelle Begegnungen',
      role_en: 'Project Manager Intercultural Encounters',
      email: 'interkulturell@kulturbruecke-mainz.de',
      preferredMethod: 'email',
      responseTime: 'Innerhalb von 48 Stunden',
      responseTime_en: 'Within 48 hours',
    },
    createdAt: new Date('2025-12-04'),
    updatedAt: new Date('2025-12-04'),
  },
  {
    id: 'chal-team-5',
    organizationId: 'org-5',
    organization: MOCK_ORGANIZATIONS[4],
    title: 'Erste-Hilfe-Kurs-Begleitung',
    title_en: 'First aid course assistance',
    description: 'Begleitet als Team einen Erste-Hilfe-Kurs und unterstützt die Kursleiter bei praktischen Übungen.',
    description_en: 'Assist a first aid course as a team and support the instructors with practical exercises.',
    instructions: '1. Bildet ein Team von 2-3 Personen\n2. Meldet euch für einen Kurstermin an (siehe Zeitslots)\n3. Unterstützt die Kursleiter bei der Vorbereitung und den Übungen\n4. Betreut die Teilnehmer während der praktischen Einheiten\n5. Macht Fotos (mit Einverständnis) und ladet sie hoch',
    instructions_en: '1. Form a team of 2-3 people\n2. Register for a course date (see time slots)\n3. Support the instructors with preparation and exercises\n4. Assist participants during practical sessions\n5. Take photos (with consent) and upload them',
    category: 'health',
    type: 'onsite',
    durationMinutes: 30,
    verificationMethod: 'photo',
    maxParticipants: 15,
    currentParticipants: 3,
    xpReward: 65,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400',
    tags: ['team', 'gesundheit', 'erste-hilfe', 'kurs'],
    isMultiPerson: true,
    minTeamSize: 2,
    maxTeamSize: 3,
    teamDescription: 'Gemeinsam lernt ihr auch etwas dabei! Ideal für Studierende mit Interesse an Medizin.',
    teamDescription_en: 'You learn something too! Ideal for students interested in medicine.',
    allowSoloJoin: true,
    teammateSeekers: [MOCK_TEAMMATE_SEEKERS[0]],
    location: {
      name: 'DRK Schulungszentrum Wiesbaden',
      name_en: 'Red Cross Training Center Wiesbaden',
      address: 'Abraham-Lincoln-Straße 7, 65189 Wiesbaden',
      meetingPoint: 'Eingang Schulungszentrum, Anmeldung',
      meetingPoint_en: 'Training center entrance, registration',
      additionalInfo: 'Bequeme Kleidung tragen. Keine Vorkenntnisse erforderlich.',
      additionalInfo_en: 'Wear comfortable clothing. No prior knowledge required.',
      coordinates: { lat: 50.0782, lng: 8.2397 },
    },
    schedule: {
      type: 'recurring',
      timeSlots: ['Sa: 9-12 Uhr (Grundkurs)', 'Sa: 14-17 Uhr (Auffrischung)'],
      deadline: new Date('2026-03-31'),
      isFlexible: false,
    },
    contact: {
      name: 'Thomas Rettung',
      role: 'Ausbildungsleiter',
      role_en: 'Training Director',
      email: 'ausbildung@drk-hessen.de',
      phone: '+49 611 5060100',
      preferredMethod: 'phone',
      responseTime: 'Innerhalb von 24 Stunden',
      responseTime_en: 'Within 24 hours',
    },
    createdAt: new Date('2025-12-05'),
    updatedAt: new Date('2025-12-05'),
  },
];

// ============================================
// MOCK USERS - Based on PRD Student Personas
// ============================================

// S1: "The Time-Pressed" - Max, 24, Master's Business Informatics, Darmstadt
// Primary demo user - represents 50% of target audience
export const MOCK_USER: User = {
  id: 'user-max',
  email: 'max.mustermann@student.tu-darmstadt.de',
  name: 'Max Mustermann',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MaxPro',
  bio: 'Master Wirtschaftsinformatik @ TU Darmstadt | 15h Werkstudent | Helfe in kleinen Zeitfenstern 🌱',
  interests: ['environment', 'education', 'health'],
  xpTotal: 280,
  level: 'helper',
  completedChallenges: 12,
  hoursContributed: 3.5,
  badges: [
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'first-challenge')!,
      earnedAt: new Date('2025-11-05'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'five-challenges')!,
      earnedAt: new Date('2025-11-15'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'ten-challenges')!,
      earnedAt: new Date('2025-11-28'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'eco-warrior')!,
      earnedAt: new Date('2025-11-25'),
    },
  ],
  savedChallengeIds: ['chal-3', 'chal-9'],
  createdAt: new Date('2025-11-01'),
  onboardingCompleted: true,
};

// S2: "The Social Helper" - Lena, 22, Bachelor's Social Work, Frankfurt
// Represents users who want to help with friends (30% of target)
export const MOCK_USER_LENA: User = {
  id: 'user-lena',
  email: 'lena.fischer@student.uni-frankfurt.de',
  name: 'Lena Fischer',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LenaHeart',
  bio: 'Soziale Arbeit @ Goethe-Uni | Engagement macht zusammen mehr Spaß! 💜',
  interests: ['social', 'education', 'culture'],
  xpTotal: 520,
  level: 'supporter',
  completedChallenges: 18,
  hoursContributed: 6.5,
  badges: [
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'first-challenge')!,
      earnedAt: new Date('2025-10-20'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'five-challenges')!,
      earnedAt: new Date('2025-11-01'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'ten-challenges')!,
      earnedAt: new Date('2025-11-15'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'social-butterfly')!,
      earnedAt: new Date('2025-11-20'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'week-streak')!,
      earnedAt: new Date('2025-11-25'),
    },
  ],
  savedChallengeIds: ['chal-4', 'chal-10'],
  createdAt: new Date('2025-10-15'),
  onboardingCompleted: true,
};

// S3: "The Achievement Hunter" - Tim, 21, Bachelor's Computer Science, Munich
// Represents gamification-motivated users (20% of target)
export const MOCK_USER_TIM: User = {
  id: 'user-tim',
  email: 'tim.weber@student.tum.de',
  name: 'Tim Weber',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TimGamer',
  bio: 'Informatik @ TUM | Collector of badges 🏆 | Level-up enthusiast',
  interests: ['environment', 'health', 'education'],
  xpTotal: 1850,
  level: 'supporter',
  completedChallenges: 45,
  hoursContributed: 15.0,
  badges: [
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'first-challenge')!,
      earnedAt: new Date('2025-09-15'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'five-challenges')!,
      earnedAt: new Date('2025-09-25'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'ten-challenges')!,
      earnedAt: new Date('2025-10-10'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'twentyfive-challenges')!,
      earnedAt: new Date('2025-11-01'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'eco-warrior')!,
      earnedAt: new Date('2025-10-20'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'health-hero')!,
      earnedAt: new Date('2025-11-10'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'week-streak')!,
      earnedAt: new Date('2025-10-28'),
    },
    {
      badge: AVAILABLE_BADGES.find((b) => b.id === 'early-bird')!,
      earnedAt: new Date('2025-11-05'),
    },
  ],
  savedChallengeIds: [],
  createdAt: new Date('2025-09-10'),
  onboardingCompleted: true,
};

// Fresh user for onboarding demo
export const MOCK_NEW_USER: User = {
  id: 'user-new',
  email: '',
  name: '',
  interests: [],
  xpTotal: 0,
  level: 'starter',
  completedChallenges: 0,
  hoursContributed: 0,
  badges: [],
  savedChallengeIds: [],
  createdAt: new Date(),
  onboardingCompleted: false,
};

// All demo users array for easy access
export const ALL_DEMO_USERS: User[] = [MOCK_USER, MOCK_USER_LENA, MOCK_USER_TIM];

// ============================================
// MOCK USER STATS
// ============================================

export const MOCK_USER_STATS: UserStats = {
  totalChallenges: 15,
  completedChallenges: 12,
  totalXp: 280,
  level: 'helper',
  hoursContributed: 3.5,
  badgesEarned: 4,
  ngosSupported: 5,
  currentStreak: 3,
  longestStreak: 7,
  challengesByCategory: {
    environment: 5,
    social: 3,
    education: 2,
    health: 1,
    animals: 1,
    culture: 0,
    other: 0,
  },
};

// ============================================
// MOCK SUBMISSIONS (for User)
// ============================================

export const MOCK_USER_SUBMISSIONS: Submission[] = [
  // In Progress
  {
    id: 'sub-1',
    challengeId: 'chal-1',
    challenge: MOCK_CHALLENGES[0],
    userId: 'user-1',
    userName: 'Max Mustermann',
    status: 'in_progress',
    proofType: 'photo',
    createdAt: new Date('2025-12-10'),
  },
  // Submitted (pending review)
  {
    id: 'sub-2',
    challengeId: 'chal-2',
    challenge: MOCK_CHALLENGES[1],
    userId: 'user-1',
    userName: 'Max Mustermann',
    status: 'submitted',
    proofType: 'photo',
    proofUrl: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400',
    caption: 'Mein Naturschutz-Post auf Instagram!',
    submittedAt: new Date('2025-12-09'),
    createdAt: new Date('2025-12-09'),
  },
  // Approved
  {
    id: 'sub-3',
    challengeId: 'chal-5',
    challenge: MOCK_CHALLENGES[4],
    userId: 'user-1',
    userName: 'Max Mustermann',
    status: 'approved',
    proofType: 'text',
    proofText: 'Hier sind meine 5 Buchempfehlungen:\n\n1. "Der kleine Wassermann" von Otfried Preußler\n2. "Momo" von Michael Ende\n3. "Die unendliche Geschichte" von Michael Ende\n4. "Emil und die Detektive" von Erich Kästner\n5. "Jim Knopf und Lukas der Lokomotivführer" von Michael Ende',
    submittedAt: new Date('2025-12-06'),
    reviewedAt: new Date('2025-12-07'),
    ngoRating: 5,
    ngoFeedback: 'Tolle Auswahl! Vielen Dank für die ausführlichen Empfehlungen.',
    xpEarned: 30,
    createdAt: new Date('2025-12-06'),
  },
];

// ============================================
// MOCK NGO ADMIN
// ============================================

export const MOCK_NGO_ADMIN: NgoAdmin = {
  id: 'admin-1',
  email: 'anna.schmidt@nabu.de',
  name: 'Anna Schmidt',
  organizationId: 'org-1',
  role: 'admin',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anna',
  createdAt: new Date('2025-01-15'),
};

// ============================================
// MOCK SUBMISSIONS (for NGO Review Queue)
// Using PRD persona names for consistency
// ============================================

export const MOCK_NGO_SUBMISSIONS: Submission[] = [
  {
    id: 'ngo-sub-1',
    challengeId: 'chal-1',
    challenge: MOCK_CHALLENGES[0],
    userId: 'user-lena',
    userName: 'Lena Fischer',
    userAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LenaHeart',
    status: 'submitted',
    proofType: 'photo',
    proofUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    caption: 'Mit meinen Freundinnen zusammen Müll gesammelt im Herrngarten! 🌿',
    submittedAt: new Date('2025-12-11T10:30:00'),
    createdAt: new Date('2025-12-11'),
  },
  {
    id: 'ngo-sub-2',
    challengeId: 'chal-2',
    challenge: MOCK_CHALLENGES[1],
    userId: 'user-tim',
    userName: 'Tim Weber',
    userAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TimGamer',
    status: 'submitted',
    proofType: 'photo',
    proofUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400',
    caption: 'Mein Instagram Post mit über 200 Likes! Challenge #15 für diesen Monat 🏆',
    submittedAt: new Date('2025-12-11T09:15:00'),
    createdAt: new Date('2025-12-11'),
  },
  {
    id: 'ngo-sub-3',
    challengeId: 'chal-1',
    challenge: MOCK_CHALLENGES[0],
    userId: 'user-max',
    userName: 'Max Mustermann',
    userAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MaxPro',
    status: 'submitted',
    proofType: 'photo',
    proofUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400',
    caption: 'Schnelle 15-Minuten-Aktion in der Mittagspause!',
    submittedAt: new Date('2025-12-10T16:45:00'),
    createdAt: new Date('2025-12-10'),
  },
  {
    id: 'ngo-sub-4',
    challengeId: 'chal-2',
    challenge: MOCK_CHALLENGES[1],
    userId: 'user-anna',
    userName: 'Anna Schneider',
    userAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AnnaStar',
    status: 'approved',
    proofType: 'photo',
    proofUrl: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400',
    submittedAt: new Date('2025-12-09T14:20:00'),
    reviewedAt: new Date('2025-12-09T18:00:00'),
    ngoRating: 5,
    ngoFeedback: 'Super kreativer Post! Vielen Dank für dein Engagement.',
    xpEarned: 20,
    createdAt: new Date('2025-12-09'),
  },
  {
    id: 'ngo-sub-5',
    challengeId: 'chal-1',
    challenge: MOCK_CHALLENGES[0],
    userId: 'user-jonas',
    userName: 'Jonas Hoffmann',
    userAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=JonasBlue',
    status: 'rejected',
    proofType: 'photo',
    proofUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400',
    submittedAt: new Date('2025-12-08T11:00:00'),
    reviewedAt: new Date('2025-12-08T15:30:00'),
    ngoFeedback: 'Das Foto zeigt leider nicht die Müllsammelaktion. Bitte reiche ein passendes Foto ein.',
    createdAt: new Date('2025-12-08'),
  },
];

// ============================================
// MOCK ORGANIZATION STATS
// ============================================

export const MOCK_ORG_STATS: OrganizationStats = {
  totalChallenges: 8,
  activeChallenges: 5,
  completedChallenges: 3,
  pendingSubmissions: 3,
  approvedSubmissions: 45,
  rejectedSubmissions: 5,
  totalVolunteerHours: 67.5,
  averageRating: 4.7,
  totalParticipants: 156,
  weeklyData: [
    { date: '2025-12-05', submissions: 12, approvals: 10 },
    { date: '2025-12-06', submissions: 8, approvals: 7 },
    { date: '2025-12-07', submissions: 15, approvals: 14 },
    { date: '2025-12-08', submissions: 6, approvals: 5 },
    { date: '2025-12-09', submissions: 9, approvals: 8 },
    { date: '2025-12-10', submissions: 11, approvals: 9 },
    { date: '2025-12-11', submissions: 7, approvals: 5 },
  ],
};

// ============================================
// HELPER FUNCTIONS
// ============================================

export const getChallengeById = (id: string): Challenge | undefined => {
  return MOCK_CHALLENGES.find((c) => c.id === id);
};

export const getOrganizationById = (id: string): Organization | undefined => {
  return MOCK_ORGANIZATIONS.find((o) => o.id === id);
};

export const getChallengesByOrganization = (orgId: string): Challenge[] => {
  return MOCK_CHALLENGES.filter((c) => c.organizationId === orgId);
};

export const getActiveChallenges = (): Challenge[] => {
  return MOCK_CHALLENGES.filter((c) => c.status === 'active');
};

export const filterChallenges = (
  challenges: Challenge[],
  filters: {
    categories?: string[];
    durations?: number[];
    types?: string[];
  }
): Challenge[] => {
  return challenges.filter((c) => {
    if (filters.categories?.length && !filters.categories.includes(c.category)) {
      return false;
    }
    if (filters.durations?.length && !filters.durations.includes(c.durationMinutes)) {
      return false;
    }
    if (filters.types?.length && !filters.types.includes(c.type)) {
      return false;
    }
    return true;
  });
};

// ============================================
// MOCK FRIENDS (for Team Challenge Invites)
// ============================================

export const MOCK_FRIENDS: Friend[] = [
  {
    id: 'friend-lena',
    name: 'Lena Fischer',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LenaHeart',
    level: 'supporter',
    xpTotal: 520,
    isFriend: true,
  },
  {
    id: 'friend-tim',
    name: 'Tim Weber',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TimGamer',
    level: 'supporter',
    xpTotal: 1850,
    isFriend: true,
  },
  {
    id: 'friend-anna',
    name: 'Anna Schneider',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AnnaStar',
    level: 'helper',
    xpTotal: 340,
    isFriend: true,
  },
  {
    id: 'friend-jonas',
    name: 'Jonas Hoffmann',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=JonasBlue',
    level: 'helper',
    xpTotal: 180,
    isFriend: true,
  },
  {
    id: 'friend-marie',
    name: 'Marie Becker',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MariePink',
    level: 'starter',
    xpTotal: 60,
    isFriend: true,
  },
  {
    id: 'friend-felix',
    name: 'Felix Braun',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FelixGreen',
    level: 'helper',
    xpTotal: 250,
    isFriend: true,
  },
];

// ============================================
// MOCK COMMUNITY POSTS
// ============================================

export const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
  // ============================================
  // SUCCESS STORIES - User-generated after verified completion
  // ============================================
  {
    id: 'post-success-1',
    type: 'success_story',
    authorType: 'user',
    authorId: 'user-lena',
    authorName: 'Lena Fischer',
    authorAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LenaHeart',
    authorLevel: 'supporter',
    title: 'Mein erster Tag bei der Tafel',
    title_en: 'My first day at the food bank',
    content: 'Heute war ich zum ersten Mal bei der Tafel zum Sortieren. Was für eine Erfahrung! Das Team war so herzlich und ich habe so viele interessante Menschen kennengelernt. Wir haben über 200 kg Lebensmittel sortiert, die sonst weggeworfen worden wären. Ich komme definitiv wieder!',
    content_en: 'Today was my first time at the food bank for sorting. What an experience! The team was so warm and I met so many interesting people. We sorted over 200 kg of food that would otherwise have been thrown away. I\'m definitely coming back!',
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800',
    linkedChallengeId: 'chal-3',
    linkedChallenge: {
      id: 'chal-3',
      title: 'Lebensmittel sortieren bei der Tafel',
      title_en: 'Sort food at the food bank',
      imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=400',
      organizationName: 'Tafel Rhein-Main e.V.',
      organizationName_en: 'Food Bank Rhine-Main',
      category: 'social',
      xpReward: 50,
      durationMinutes: 30,
    },
    submissionId: 'sub-lena-tafel',
    xpEarned: 50,
    likesCount: 96,
    userHasLiked: false,
    commentsCount: 12,
    comments: [
      {
        id: 'comment-1',
        postId: 'post-success-1',
        userId: 'user-tim',
        userName: 'Tim Weber',
        userAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TimGamer',
        userLevel: 'supporter',
        content: 'Stark Lena! Das motiviert mich, auch mal hinzugehen!',
        createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
      },
      {
        id: 'comment-2',
        postId: 'post-success-1',
        userId: 'user-max',
        userName: 'Max Mustermann',
        userAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MaxPro',
        userLevel: 'helper',
        content: 'Respekt! 200 kg ist echt viel',
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
    ],
    isHighlighted: true,
    isPinned: true,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: 'post-success-2',
    type: 'success_story',
    authorType: 'user',
    authorId: 'user-tim',
    authorName: 'Tim Weber',
    authorAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TimGamer',
    authorLevel: 'supporter',
    title: 'Challenge #45 geschafft!',
    title_en: 'Challenge #45 completed!',
    content: 'Mit der Erste-Hilfe-Info Challenge habe ich jetzt 45 Challenges abgeschlossen! Was als Zeitvertreib begann, ist zu einer echten Leidenschaft geworden. Ich habe so viele tolle Organisationen kennengelernt und dabei sogar wichtige Skills gelernt. Danke SolvTerra!',
    content_en: 'With the first aid info challenge I have now completed 45 challenges! What started as a pastime has become a real passion. I\'ve met so many great organizations and even learned important skills. Thanks SolvTerra!',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800',
    linkedChallengeId: 'chal-7',
    linkedChallenge: {
      id: 'chal-7',
      title: 'Erste-Hilfe-Wissen teilen',
      title_en: 'Share first aid knowledge',
      imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400',
      organizationName: 'Deutsches Rotes Kreuz Hessen',
      organizationName_en: 'German Red Cross Hesse',
      category: 'health',
      xpReward: 30,
      durationMinutes: 15,
    },
    submissionId: 'sub-tim-erstehilfe',
    xpEarned: 30,
    likesCount: 174,
    userHasLiked: true,
    commentsCount: 18,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    id: 'post-success-3',
    type: 'success_story',
    authorType: 'user',
    authorId: 'user-anna',
    authorName: 'Anna Schneider',
    authorAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AnnaStar',
    authorLevel: 'helper',
    title: 'Team-Challenge mit meinen besten Freunden!',
    title_en: 'Team challenge with my best friends!',
    content: 'Mit Jonas und Marie haben wir zusammen Müll im Herrngarten gesammelt. Es hat so viel Spaß gemacht! Wir haben 3 volle Müllsäcke gesammelt und dabei mega viel gelacht. Das Beste am Helfen? Es zusammen zu machen!',
    content_en: 'With Jonas and Marie we collected trash together in Herrngarten. It was so much fun! We collected 3 full trash bags and laughed a lot. The best thing about helping? Doing it together!',
    imageUrl: 'https://images.unsplash.com/photo-1567393528677-d6adae7d4a0a?w=800',
    linkedChallengeId: 'chal-team-1',
    linkedChallenge: {
      id: 'chal-team-1',
      title: 'Gemeinsame Müllsammelaktion',
      title_en: 'Team trash cleanup',
      imageUrl: 'https://images.unsplash.com/photo-1567393528677-d6adae7d4a0a?w=400',
      organizationName: 'NABU Ortsgruppe Darmstadt',
      organizationName_en: 'NABU Local Chapter Darmstadt',
      category: 'environment',
      xpReward: 75,
      durationMinutes: 30,
    },
    teamMemberNames: ['Anna', 'Jonas', 'Marie'],
    submissionId: 'sub-anna-team',
    xpEarned: 75,
    likesCount: 139,
    userHasLiked: false,
    commentsCount: 9,
    comments: [
      {
        id: 'comment-3',
        postId: 'post-success-3',
        userId: 'user-lena',
        userName: 'Lena Fischer',
        userAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LenaHeart',
        userLevel: 'supporter',
        content: 'Super Initiative! Zusammen macht alles mehr Spaß!',
        createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
  },

  // ============================================
  // AUTO-GENERATED ACTIVITY POSTS
  // ============================================
  {
    id: 'post-activity-1',
    type: 'challenge_completed',
    authorType: 'user',
    authorId: 'user-max',
    authorName: 'Max Mustermann',
    authorAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MaxPro',
    authorLevel: 'helper',
    linkedChallengeId: 'chal-1',
    linkedChallenge: {
      id: 'chal-1',
      title: 'Müllsammelaktion im Park dokumentieren',
      title_en: 'Document trash cleanup in the park',
      imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400',
      organizationName: 'NABU Ortsgruppe Darmstadt',
      organizationName_en: 'NABU Local Chapter Darmstadt',
      category: 'environment',
      xpReward: 30,
      durationMinutes: 15,
    },
    xpEarned: 30,
    likesCount: 28,
    userHasLiked: false,
    commentsCount: 2,
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000),
  },
  {
    id: 'post-activity-2',
    type: 'badge_earned',
    authorType: 'user',
    authorId: 'user-tim',
    authorName: 'Tim Weber',
    authorAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TimGamer',
    authorLevel: 'supporter',
    badgeId: 'twentyfive-challenges',
    badgeName: 'Dedicated Helper',
    badgeName_en: 'Dedicated Helper',
    badgeIcon: 'award',
    likesCount: 93,
    userHasLiked: true,
    commentsCount: 7,
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000),
  },
  {
    id: 'post-activity-3',
    type: 'level_up',
    authorType: 'user',
    authorId: 'user-jonas',
    authorName: 'Jonas Hoffmann',
    authorAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=JonasBlue',
    authorLevel: 'helper',
    newLevel: 'helper',
    likesCount: 65,
    userHasLiked: false,
    commentsCount: 5,
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000),
  },
  {
    id: 'post-activity-4',
    type: 'streak_achieved',
    authorType: 'user',
    authorId: 'user-lena',
    authorName: 'Lena Fischer',
    authorAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LenaHeart',
    authorLevel: 'supporter',
    streakDays: 7,
    likesCount: 85,
    userHasLiked: false,
    commentsCount: 6,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: 'post-activity-5',
    type: 'challenge_completed',
    authorType: 'user',
    authorId: 'user-felix',
    authorName: 'Felix Braun',
    authorAvatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FelixGreen',
    authorLevel: 'helper',
    linkedChallengeId: 'chal-team-2',
    linkedChallenge: {
      id: 'chal-team-2',
      title: 'Team-Recherche: Bildungsmaterialien',
      title_en: 'Team research: Educational materials',
      imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400',
      organizationName: 'Bildungsinitiative Frankfurt',
      organizationName_en: 'Education Initiative Frankfurt',
      category: 'education',
      xpReward: 45,
      durationMinutes: 15,
    },
    teamMemberNames: ['Felix', 'Tim'],
    xpEarned: 45,
    likesCount: 57,
    userHasLiked: false,
    commentsCount: 4,
    createdAt: new Date(Date.now() - 28 * 60 * 60 * 1000),
  },
];

// ============================================
// HELPER FUNCTIONS FOR COMMUNITY
// ============================================

export const getCommunityPostById = (id: string): CommunityPost | undefined => {
  return MOCK_COMMUNITY_POSTS.find((p) => p.id === id);
};

export const getUserSuccessStories = (userId?: string): CommunityPost[] => {
  const stories = MOCK_COMMUNITY_POSTS.filter((p) => p.type === 'success_story');
  return userId ? stories.filter((s) => s.authorId === userId) : stories;
};

export const getPinnedPosts = (): CommunityPost[] => {
  return MOCK_COMMUNITY_POSTS.filter((p) => p.isPinned);
};

export const getHighlightedPosts = (): CommunityPost[] => {
  return MOCK_COMMUNITY_POSTS.filter((p) => p.isHighlighted);
};
